# The limit of lives a player can have. Player lives reset/default to this
livesLimit: 4

# The amount of time until a player's lives are reset
updateInterval: 24

# The amount of time a player will be banned for once they run out of lives
banLength: 24

# The reason passed into AdvancedBan when a player is banned
banReason: "@deathban"

# How many lives a player will lose when they die by a player
playerDeathCost: 2

# How many lives a player will lose when they die by a non-player
nonPlayerDeathCost: 1
