name: Deathban
version: "${project.version}"
main: com.jamesalin.deathban.Deathban
api-version: 1.19

permissions:
  bypass:
    description: Bypasses the deathban restrictions
    default: op

commands:
  deaths:
    description: Shows the amount of times you lost lives
    usage: /deaths [@OPTIONAL page]
    aliases: [deathc, deathcount]
