name: Deathban
description: A plugin that allows you to ban players for a certain amount of time after they die a certain amount of times
version: "${project.version}"
author: James Linimik
website: https://github.com/Jameslinimk/deathban
main: com.jamesalin.deathban.Deathban
api-version: 1.19
depend: [ AdvancedBan, LuckPerms ]

permissions:
  deathban.bypass:
    description: Bypasses the deathban restrictions
    default: op
  deathban.editlives:
    description: Allows the user to edit the amount of lives a player has
    default: op
  deathban.seethrough:
    description: Allows the user to see the lives of other players even if they are hidden
    default: op

commands:
  deaths:
    description: Shows the amount of times you lost lives
    usage: /deaths [page]
    aliases: [ deathc, deathcount ]
  lives:
    description: Shows the amount of lives you or another player have
    usage: /lives [player]
    aliases: [ lvs, livecount ]
  editlives:
    description: Edits the amount of lives a player has
    usage: /editlives <player> <amount>
    permission: deathban.editlives
    aliases: [ editlvs, editlivecount ]
  showlives:
    description: Makes your lives visible to other players
    usage: /showlives
    aliases: [ showlvs, showlivecount ]
  hidelives:
    description: Hides your lives from other players
    usage: /hidelives
    aliases: [ hidelvs, hidelivecount ]
